version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

commands:
  publish:
    steps:
      - checkout
      - aws-cli/setup
      - run: ./publish.sh

jobs:
  us_east_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: us-east-1
    steps:
      - publish

workflows:
  version: 2
  publish:
    jobs:
      - us_east_1:
          context: apache-tika-lambda-layer
          filters:
            branches:
              only:
                - master
